### ISSUE TITLE
Setup Nuget Package (pre-release)

### ISSUE THREAD

**Issue by Tasteful** [StubbleOrg/Stubble.Helpers#1]
Do you have any plan to release this as an nuget-package (pre-release will work) that can be used?

**Comment by Romanx** [comment]
Hi there,

It's been on my list to do but I've been unfortunately very slack. I'll aim to get this done (in a pre-release state) this week but if you'd like to use it before then you can download the package from appveyor [here](https://ci.appveyor.com/project/Romanx/stubble-helpers/branch/master/artifacts)

Thanks for showing interest, please feel free to open issues about any problems you find.

**Comment by Romanx** [comment]
Hi there, 

Thank you for being patient. This is now being pushed to nuget when the master branch is updated: https://www.nuget.org/packages/Stubble.Helpers/

Thanks,
