### ISSUE TITLE
Static arguments will be replaced by tokens

### ISSUE THREAD

**Issue by Tasteful** [StubbleOrg/Stubble.Helpers#10]
Hi,
For the PR with the static arguments I had the following test that was ensuring that a static text can be the same as an token that should be replaced.

When the change in the `HelperTagParser.ParseQuotedString` to already here remove the quotation around the string we don't know when we should do the lookup if the token is a static text that not should be replaced or a token that should be replaced and will replace both of them.

If we can change the `HelperToken.Args` to an `object[]` instead, then the parsed static token can be added as an `Func<string>` and be used instead of doing the lookup.

Current result
```
Message: Assert.Equal() Failure
           ↓ (pos 1)
Expected: <Count#10>
Actual:   <10#10>
           ↑ (pos 1)
```

Test
```
        [Theory]
        [InlineData("'Count'", '\'')]
        [InlineData("\"Count\"", '"')]
        public void ItShouldCallHelperWhenExistsStaticAndDynamicVariable(string inputData, char trimCharacter)
        {
            var writer = new StringWriter();
            var settings = new RendererSettingsBuilder().BuildSettings();
            var renderSettings = new RenderSettings();
            var stringRenderer = new StringRender(writer, settings.RendererPipeline);

            var helpers = ImmutableDictionary.CreateBuilder<string, HelperRef>();

            var helper = new Func<HelperContext, string, int, string>((helperContext, staticVariable, dynamicVariable) =>
            {
                return $"<{staticVariable}#{dynamicVariable}>";
            });

            helpers.Add("MyHelper", new HelperRef(helper));

            var tagRenderer = new HelperTagRenderer(helpers.ToImmutable());

            var token = new HelperToken
            {
                Name = "MyHelper",
                Args = new[] { inputData, "Count" }
            };

            var context = new Context(new { Count = 10 }, settings, renderSettings);

            tagRenderer.Write(stringRenderer, token, context);

            var res = writer.ToString();

            Assert.Equal($"<{inputData.Trim(trimCharacter)}#10>", res);
        }
```

**Comment by Romanx** [comment]
I'm not sure it's the most intuitive option that a static argument would take precedence over a context value.

I think the best option here would to note it in the readme and recommend using different names

**Comment by Tasteful** [comment]
The main purpose of the static-arguments was the ability to pass strings in that not should be replaced. I'm also unsecure aboute how this replacement will work if you set the settings to throw exception if replacement keys not exists (not able to test right now).

**Comment by Romanx** [comment]
Hi there,

Sorry for the delay in replying to this. I did some thinking and think that you're right and if you quoted something you want it treated verbatim.

The change I just made will treat quoted values as constants (but will still type convert) and otherwise will attempt context lookup.

This can probably be refined as currently it would still lookup a value for the unquoted `10` however this is technically a possible key in a dictionary so still valid.

Please let me know if you find any issues with the approach in your use case and any other issues you may have.

Thanks very much for being an alpha user of this library
![](https://media.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif)
