### ISSUE TITLE
Helpers does not work with Stubble 1.4.12

### ISSUE THREAD

**Issue by jirikopecky** [StubbleOrg/Stubble.Helpers#11]
When I update stubble, helpers stops working. Further investigation shows that the `AddHelpers` method does not register `HelperTagParser` properly.

I think it should be using the new `ConfigureParserPipeline` method, but that is just a guess.

**Comment by Romanx** [comment]
Hi there,

Thanks for reporting this. I should be able to take a look and push a fix later today

**Comment by Romanx** [comment]
Hey,

Thanks again for reporting this. It was fixed in the related commit and a new pre-release version has been pushed to nuget as version `1.0.16-g81ee0be16b`

Please let us know if you find anymore issues.

**Comment by jirikopecky** [comment]
Thank you for such a quick fix!
