### ISSUE TITLE
Not found value results in passing argument into helper delegate

### ISSUE THREAD

**Issue by petermicuch** [StubbleOrg/Stubble.Helpers#22]
In case input object does not contain reference from template (lookup is NULL), instead of passing NULL as parameter to registered helper function, complete reference is passed in instead. Was this intention? Because rendered template results are different depending if you use helper or not.

Code in HelperTagRenderer:
if (value is null)
            {
                // When lookup is null we should use the argument as passed
                value = arg;
            }

Example template with and without helper:
User nickname is {{user.nickname}}.
User nickname is {{ToCapitalLetters user.nickname}}

Input json object (using JsonNet extension) does not contain property nickname:
{ "user" : { "name" : "John", "surname" : "Doe" } }
Results:
User nickname is NULL.
User nickname is USER.NICKNAME

Helper has no way to find if passed value is real value for conversion or if it is invalid. To be consistent with the behavior of without helpers, I think this should be corrected. There is no reasoning in the code really, only comment that it should be like that. Why is it so? Is there assumption that someone might want to interpret reference on his own? Does this introduce unnecessary lookup then?

**Comment by Romanx** [comment]
Hi there,

I've just been taking a quick look at this, I think it may be related to an interaction between the `JSON.Net` extension and the helpers extension. If you could you possibly give me a stripped down reproduction I should be able to look at this.

**Comment by petermicuch** [comment]
Hi,

the issue is in the HelperTagRenderer as I described in original post. In case reference is not resolved (null is returned) it simply sets argument as the value. This is not really related to json being used as input, the same would be true for any object as well as long as you use helpers.

Here is sample code without using JSON.Net extension to see that it is no related to that and that problem is in the HelperTagRenderer:
```
public sealed class TestObject
{
    public string Name { get; set; } = "John";
}

class Test
{
    [Test]
    public void RenderingTests()
    {
        Helpers helpers = new Helpers().Register("ToCapitalLetters", (HelperContext context, string args) => args.ToUpper());
        var stubbleVisitor = new StubbleBuilder().Configure(settings =>
        {
            settings.AddHelpers(helpers);
        }).Build();

        TestObject testObject = new TestObject();
        string result = stubbleVisitor.Render(
            "User name is '{{Name}}' and nickname is '{{Nickname}}'." +
                    "In capital letters name is '{{ToCapitalLetters Name}}' and nickname is '{{ToCapitalLetters Nickname}}'",
            testObject);
        Assert.AreEqual("User name is 'John' and nickname is ''.In capital letters name is 'JOHN' and nickname is 'NICKNAME'", result);
    }
}
```
When you run this test, it will pass and that is wrong. You can check the Assert to see what the resulting string looks like.

Assert should actually expect text like the one below and then the test will be correct:
```
"User name is 'John' and nickname is ''.In capital letters name is 'JOHN' and nickname is ''"
```

**Comment by Romanx** [comment]
@petermicuch Thanks for your response and great reproduction case. The logic here wasn't clear but it existed so that constants could be passed into helpers as arguments such as `10` or `20.21` and be type converted into an argument.

This fell down with the lookup and string types since it would pass the key through as though it were a constant you wanted to be looked up. I've changed the behavior now so that value types will have attempted conversion by default and string must be quoted for constants so they are not valid for look up.

Hopefully this makes some sense, I'll get a release out with the change shortly. Please let me know if you have any issues with it.

**Comment by petermicuch** [comment]
@Romanx Thanks for the fix. For the case I provided this works fine. If I understand correctly, anytime I quote input parameter of helper, there is not lookup done at all. That sounds reasonable.

BTW - there is not license file in the Helpers repo unlike in Core and JsonNet extension. Would you mind adding one?

**Comment by Romanx** [comment]
Thanks very much for the heads up about the license. Will add an issue for it now
